# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# describe ReactionsController do
#   render_views

#   # This should return the minimal set of attributes required to create a valid
#   # Reaction. As you add validations to Reaction, be sure to
#   # update the return value of this method accordingly.
#   def valid_attributes
#     {}
#   end
  
#   # This should return the minimal set of values that should be in the session
#   # in order to pass any filters (e.g. authentication) defined in
#   # ReactionsController. Be sure to keep this updated too.
#   def valid_session
#     {}
#   end

#   describe "GET index" do
#     it "assigns all reactions as @reactions" do
#       reaction = Reaction.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:reactions).should eq([reaction])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested reaction as @reaction" do
#       reaction = Reaction.create! valid_attributes
#       get :show, {:id => reaction.to_param}, valid_session
#       assigns(:reaction).should eq(reaction)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new reaction as @reaction" do
#       get :new, {}, valid_session
#       assigns(:reaction).should be_a_new(Reaction)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested reaction as @reaction" do
#       reaction = Reaction.create! valid_attributes
#       get :edit, {:id => reaction.to_param}, valid_session
#       assigns(:reaction).should eq(reaction)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new Reaction" do
#         expect {
#           post :create, {:reaction => valid_attributes}, valid_session
#         }.to change(Reaction, :count).by(1)
#       end

#       it "assigns a newly created reaction as @reaction" do
#         post :create, {:reaction => valid_attributes}, valid_session
#         assigns(:reaction).should be_a(Reaction)
#         assigns(:reaction).should be_persisted
#       end

#       it "redirects to the created reaction" do
#         post :create, {:reaction => valid_attributes}, valid_session
#         response.should redirect_to(Reaction.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved reaction as @reaction" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         Reaction.any_instance.stub(:save).and_return(false)
#         post :create, {:reaction => {}}, valid_session
#         assigns(:reaction).should be_a_new(Reaction)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         Reaction.any_instance.stub(:save).and_return(false)
#         post :create, {:reaction => {}}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested reaction" do
#         reaction = Reaction.create! valid_attributes
#         # Assuming there are no other reactions in the database, this
#         # specifies that the Reaction created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         Reaction.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#         put :update, {:id => reaction.to_param, :reaction => {'these' => 'params'}}, valid_session
#       end

#       it "assigns the requested reaction as @reaction" do
#         reaction = Reaction.create! valid_attributes
#         put :update, {:id => reaction.to_param, :reaction => valid_attributes}, valid_session
#         assigns(:reaction).should eq(reaction)
#       end

#       it "redirects to the reaction" do
#         reaction = Reaction.create! valid_attributes
#         put :update, {:id => reaction.to_param, :reaction => valid_attributes}, valid_session
#         response.should redirect_to(reaction)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the reaction as @reaction" do
#         reaction = Reaction.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         Reaction.any_instance.stub(:save).and_return(false)
#         put :update, {:id => reaction.to_param, :reaction => {}}, valid_session
#         assigns(:reaction).should eq(reaction)
#       end

#       it "re-renders the 'edit' template" do
#         reaction = Reaction.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         Reaction.any_instance.stub(:save).and_return(false)
#         put :update, {:id => reaction.to_param, :reaction => {}}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested reaction" do
#       reaction = Reaction.create! valid_attributes
#       expect {
#         delete :destroy, {:id => reaction.to_param}, valid_session
#       }.to change(Reaction, :count).by(-1)
#     end

#     it "redirects to the reactions list" do
#       reaction = Reaction.create! valid_attributes
#       delete :destroy, {:id => reaction.to_param}, valid_session
#       response.should redirect_to(reactions_url)
#     end
#   end

# end
